export class Interaction {
  checkdatepriseencompte?: string;
  commentaire?: string;
  custcode?: any;
  dateCM?: string;
  date_creation?: string;
  date_modification?: string;
  date_prise_compte?: string;
  date_valide?: string;
  description_courte?: string;
  etape?: string;
  etat?: string;
  id?: any;
  idActe?: any;
  idAction?: any;
  idRole?: any;
  id_interaction?: string;
  id_relance?: any;
  id_reutilisable?: any;
  initiateur?: string;
  input?: any;
  lblAction?: string = '';
  lblraison?: string;
  nbligne?: any;
  nom_fichier?: string;
  parametre?: string;
  plan_tarifaire?: any;
  result?: any;
  service_a_modifier?: any;
  service_param?: any;
}
